singleQuote: true
semi: false
printWidth: 100
trailingComma: none
tabWidth: 2
useTabs: false
quoteProps: 'as-needed'
arrowParens: 'always'
endOfLine: 'lf'
bracketSpacing: true
jsxBracketSameLine: false
requirePragma: false
insertPragma: false
proseWrap: 'preserve'
